version: 2
jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Install & lint & test
          command: |
            sudo npm install -g firebase-tools
            sudo npm install -g @angular/cli@latest
            cd functions; npm install; cd ..
            ng lint
            ng test --code-coverage
      - run:
          name: Prepare for deployment
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
            ng build --aot --prod --base-href https://khien-fe-test.firebaseapp.com/; fi
      - run:
          name: Deploy app to firebase
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then firebase deploy --project khien-fe-test --token=$FIREBASE_DEPLOY_TOKEN; fi
workflows:
  version: 2
  workflow:
    jobs:
      - build
